name: Build and Publish Remote-Vector-Index-Builder Core Snapshot Image to Docker

on:
  push:
    branches:
      - main
    paths:
      - 'remote_vector_index_builder/core/**'
      - '.github/workflows/publish_remote_core_image.yml'
  pull_request:
    paths: # Note this is done for folder specific checkouts, reduce CI memory load
      - 'remote_vector_index_builder/**'
      - 'test_remote_vector_index_builder/**'
      - 'e2e/**'
      - '.github/workflows/publish_remote_core_image.yml'

  workflow_call: # enables workflow to be reused
    secrets:
      REMOTE_VECTOR_DOCKER_USERNAME:
        required: true
      REMOTE_VECTOR_DOCKER_PASSWORD:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-core-image:
    name: Build and Publish Remote-Vector-Index-Builder Core Snapshot Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build Docker Image
        run : |
          docker build  -f ./remote_vector_index_builder/core/Dockerfile . -t opensearchstaging/remote-vector-index-builder:core-snapshot

      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}
          password: ${{ secrets.REMOTE_VECTOR_DOCKER_PASSWORD }}

      - name: Push Docker Image
        run : |
          docker push ${{secrets.REMOTE_VECTOR_DOCKER_USERNAME}}/remote-vector-index-builder:core-snapshot
      - name: Runner Cleanups
        if: always()
        uses: ./.github/actions/docker-cleanup
        with:
          workspace: ${{ github.workspace }}
  
  # Trigger the build of core image since api image is changed
  build-and-publish-api-image:
    needs: build-and-publish-core-image
    uses: ./.github/workflows/publish_remote_api_image.yml
    secrets:
      REMOTE_VECTOR_DOCKER_ROLE: ${{ secrets.REMOTE_VECTOR_DOCKER_ROLE }}
      REMOTE_VECTOR_DOCKER_USERNAME: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}