name: Build and Publish Remote-Vector-Index-Builder API Image to Docker

on:
  push:
    paths:
      - 'remote_vector_index_builder/app/**'
      - '.github/workflows/publish_remote_api_image.yml'

  workflow_call: # enables workflow to be reused
    secrets:
      REMOTE_VECTOR_DOCKER_USERNAME:
        required: true
      REMOTE_VECTOR_DOCKER_PASSWORD:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-api-image:
    name: Build and Publish Remote-Vector-Index-Builder API Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build Docker Image
        run : |
          docker build  -f ./remote_vector_index_builder/app/Dockerfile . -t opensearchstaging/remote-vector-index-builder:api-snapshot

      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}
          password: ${{ secrets.REMOTE_VECTOR_DOCKER_PASSWORD }}

      - name: Push Docker Image
        run : |
          docker push ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}/remote-vector-index-builder:api-snapshot
      - name: Runner Cleanups
        if: always()
        uses: ./.github/actions/docker-cleanup
        with:
          workspace: ${{ github.workspace }}